### ISSUE TITLE
Does not work in webui 1.4

### ISSUE THREAD

**Issue by ZerasSunn** [Coyote-A/ultimate-upscale-for-automatic1111#109]
It report error on version 1.4, but worked normaly again when I rolled back to version 1.3.2. 
Here's the error text in webui: 

TypeError: Script.run() missing 18 required positional arguments: '_', 'tile_width', 'tile_height', 'mask_blur', 'padding', 'seams_fix_width', 'seams_fix_denoise', 'seams_fix_padding', 'upscaler_index', 'save_upscaled_image', 'redraw_mode', 'save_seams_fix_image', 'seams_fix_mask_blur', 'seams_fix_type', 'target_size_type', 'custom_width', 'custom_height', and 'custom_scale'

Seems like the ultimate upscale is totally missing.
And here's the full error report in the console, most of them looks like data of another extensions to me, but I'm not sure, maybe those are helpful?

*** Error completing request
*** Arguments: ('task(m1tzbpmw6qcm8s2)', 0, '', '', [], <PIL.Image.Image image mode=RGBA size=512x768 at 0x26933A4A9E0>, None, None, None, None, None, None, 20, 0, 4, 0, 1, False, False, 1, 1, 7, 1.5, 0.75, -1.0, -1.0, 0, 0, 0, False, 1, 512, 512, 2, 0, 0, 32, 0, '', '', '', [], 12, False, {'ad_model': 'mediapipe_face_full', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0, 'ad_controlnet_guidance_end': 1}, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 1536, 96, True, True, True, False, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, 1.6, 0.97, 0.4, 0, 20, 0, 12, '', True, False, False, False, 512, False, True, ['Face'], False, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000026933CFFEB0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000026930F23AC0>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000026933960040>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000026933961030>, <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x0000026930F21270>, False, '', 0.5, True, False, '', 'Lerp', False, False, False, 0, None, [], 0, False, [], [], False, 0, 1, False, False, 0, None, [], -2, False, [], False, 0, None, None, False, False, False, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 20, '<ul>\n<li><code>CFG Scale</code> should be 2 or lower.</li>\n</ul>\n', True, True, '', '', True, 50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8, ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False, False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale the image by the selected scale factor; use width and height sliders to set tile size</p>', 64, 0, 2, 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, 1.6, 0.97, 0.4, 0, 20, 0, 12, '', True, False, False, False, 512, False, True, ['Face'], False, None, None, False, None, None, False, None, None, False, None, None, False, None, None, False, 50, '', 2, True, 'Wavelet', False, '<p style="margin-bottom:0.75em">Will upscale the image depending on the selected target size type</p>', 512, 0, 8, 32, 64, 0.35, 32, 6, True, 0, False, 8, 0, 0, 2048, 2048, 2) {}
    Traceback (most recent call last):
      File "D:\Program Files\StableDiffusion\stable-diffusion-webui\modules\call_queue.py", line 55, in f
        res = list(func(*args, **kwargs))
      File "D:\Program Files\StableDiffusion\stable-diffusion-webui\modules\call_queue.py", line 35, in f
        res = func(*args, **kwargs)
      File "D:\Program Files\StableDiffusion\stable-diffusion-webui\modules\img2img.py", line 196, in img2img
        processed = modules.scripts.scripts_img2img.run(p, *args)
      File "D:\Program Files\StableDiffusion\stable-diffusion-webui\modules\scripts.py", line 456, in run
        processed = script.run(p, *script_args)
    TypeError: Script.run() missing 18 required positional arguments: '_', 'tile_width', 'tile_height', 'mask_blur', 'padding', 'seams_fix_width', 'seams_fix_denoise', 'seams_fix_padding', 'upscaler_index', 'save_upscaled_image', 'redraw_mode', 'save_seams_fix_image', 'seams_fix_mask_blur', 'seams_fix_type', 'target_size_type', 'custom_width', 'custom_height', and 'custom_scale'

**Comment by buckwheaton** [comment]
Happening to me too.

**Comment by alenknight** [comment]
i have the same issue.  busted for me too.

**Comment by ggyydream** [comment]
same issue at web UI 1.4
 version: [v1.4.0]•  python: 3.10.9  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: [a77aa87aa3]

**Comment by dhwz** [comment]
Hires fix is also broken if ultimate upscale extension is enabled (the the menu options no longer popup)

**Comment by ggyydream** [comment]
> same issue at web UI 1.4 version: [v1.4.0]•  python: 3.10.9  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: [a77aa87aa3]

When I removed sd-webui-mov2mov, ultimate-upscale-for-automatic1111 is work.

**Comment by wade-wws** [comment]
removing mov2mov resolved it for me as well.

**Comment by CallMeSaoX** [comment]
Unbelievable, removing mov2mov solved the same problem for me.

**Comment by ZerasSunn** [comment]
> > same issue at web UI 1.4 version: [v1.4.0]•  python: 3.10.9  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: [a77aa87aa3]
> 
> When I removed sd-webui-mov2mov, ultimate-upscale-for-automatic1111 is work.

Wow that's...fantastic, beyond my comprehension. Thank you for help! And no need to remove, just disable mov2mov will do too. Still, hope this issue is officially fixed.

**Comment by photodarren** [comment]
I don't have mov2mov installed so I can't remove it to fix the problem. I wonder if it wasn't mov2mov, but the act of removing it that refreshed something?
